"""Generate an EU AI Act Annex IV technical-documentation skeleton (Markdown).

Annex IV of Regulation (EU) 2024/1689 lists the technical documentation required for
high-risk AI systems (referenced by Article 11). This module produces a structured
draft pre-filled with everything we can derive from the scan/classification and clearly
flagged ``[TODO: ...]`` where human input is required.

It is a starting scaffold to accelerate documentation - not a finished technical file.
"""
from __future__ import annotations

import datetime as _dt
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .scanner import ScanResult
    from .classifier import ClassificationResult


def _component_table(scan: "ScanResult") -> str:
    if not scan.components:
        return "_No AI components detected._\n"
    rows = ["| Component | Kind | Category | Vendor | Version | Notes |",
            "|---|---|---|---|---|---|"]
    for c in scan.components:
        rows.append(
            f"| {c.name} | {c.kind} | {c.category} | {c.vendor or '—'} "
            f"| {c.version or '—'} | {(c.risk_note or '').replace('|', '/')} |"
        )
    return "\n".join(rows) + "\n"


def generate_annex_iv(scan: "ScanResult", classification: "ClassificationResult",
                      *, system_name: str = "AI System") -> str:
    """Return a Markdown Annex IV technical-documentation draft."""
    today = _dt.date.today().isoformat()
    todo = "**[TODO: complete this section]**"

    return f"""# Annex IV Technical Documentation — {system_name}

> Draft generated by AIBOM-Guard on {today}. Sections marked {todo} require human
> input. This scaffold maps to Annex IV of Regulation (EU) 2024/1689 and is **not** a
> substitute for legal review or a conformity assessment.

**Provisional EU AI Act risk tier:** `{classification.tier}` ({classification.status}, confidence: {classification.confidence})
{classification.rationale}

---

## 1. General description of the AI system

1.1 **Intended purpose.** {todo} — describe what the system does and the problem it solves.
1.2 **Provider / deployer.** {todo} — legal entity, contact, role (provider vs deployer).
1.3 **Versions and date.** System version {todo}; documentation date {today}.
1.4 **How the system interacts with hardware/software.** {todo}
1.5 **User interface for the deployer.** {todo}

## 2. Detailed description of elements and development process

2.1 **Methods and steps for development.** {todo} — incl. any pre-trained/third-party systems used.
2.2 **Design specifications & system architecture.** {todo}
2.3 **AI components inventory (from AI-BOM).**

{_component_table(scan)}

2.4 **Computational resources** used to develop, train, test, validate. {todo}
2.5 **Data requirements / datasheets.** {todo} — provenance, scope, characteristics, labelling, cleaning, bias analysis (see ISO 42001 A.7.5).
2.6 **Human oversight assessment** (Article 14). {todo} — measures enabling human oversight; interpretability.
2.7 **Predetermined changes & continuous compliance.** {todo}
2.8 **Validation & testing procedures and metrics** (incl. accuracy, robustness, fairness). {todo}
2.9 **Cybersecurity measures** (Article 15). {todo}

## 3. Monitoring, functioning and control

3.1 **Capabilities and limitations**, expected accuracy, foreseeable risks. {todo}
3.2 **Foreseeable unintended outcomes** and risks to health/safety/fundamental rights. {todo}
3.3 **Human oversight measures in operation.** {todo}
3.4 **Input data specifications.** {todo}

## 4. Risk management system (Article 9)

4.1 Description of the risk management system and how risks were addressed. {todo}

## 5. Lifecycle changes

5.1 Description of any changes made through the system's lifecycle. {todo}

## 6. Standards and specifications applied

6.1 Harmonised standards / common specifications applied (e.g. ISO/IEC 42001). {todo}

## 7. EU declaration of conformity

7.1 Copy of the EU declaration of conformity. {todo}

## 8. Post-market monitoring (Article 72)

8.1 Description of the post-market monitoring plan and system. {todo}
8.2 **Event logging** (Article 12) — retention of automatically generated logs for **at least 6 months** for high-risk systems. {todo} — confirm logging location is under your control.

---

### Appendix A — Detected AI components (raw)

This appendix is auto-maintained from the AI-BOM. Keep it in sync each release.

{_component_table(scan)}
"""
